### PR TITLE
Contribution policies

### PR DESCRIPTION
**Pull request by aquiles23**
## Issue

Related to issue #6 

## Notes
The issue templates and the code of conduct are the same recommended by GitHub, 
The pull request template is simple and similar to this PR,
If you need an extra step on the contribute guide, like `comment a issue to show interest in that issue` let me know.

### CODE REVIEW

**Comment by aquiles23** [comment]
A alternative way to see if a person already take a issue, is to make draft of pull request while working in the issue. It can be on the contribution guide or the the act of comment in a issue before work on it.

**Comment by mansogf** [comment]
@aquiles23 , regarding what you said in the last comment, it would be great if:

- the person who is interested in working on an issue puts the [WIP] flag in the PR title **and** also writes a comment in the issue to signalize the interest.

**Comment by aquiles23** [comment]
I made obligatory to work on a issue to track the problem.

@mansogf i don't see any options to add a [WIP] tag, most of the searches i made point to make a draft of a PR like in [this].(https://github.blog/2019-02-14-introducing-draft-pull-requests/),

Also i found a [third-party application](https://github.com/apps/wip) that makes that but it is not in this repo.

I put the draft option since it is built-in. if this is what you want I'm done here :smiley: .

**Comment by mansogf** [comment]
@aquiles23 , the [WIP] flag must be in the title of the PR while you are working on it and not done. It can be done manually. Once the issue work is done, the contributors can click on "Edit" and remove the [WIP] flag from the PR title.

**Comment by aquiles23** [comment]
@mansogf done.

**Comment by mansogf** [comment]
You're good to go =P

**Pull request merged**
